name: scan
on:
  repository_dispatch:
     inputs:
        P_ID:
          description: 'P_ID'
          required: false
        P_KEY:
          description: 'P_KEY'
          required: false
        P_ADD:
          description: 'P_ADD'
          required: false
         
 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Parameters
        run: |
         echo "P_ID=${{ github.event.inputs.p_id }}" >> $GITHUB_ENV
          echo "P_KEY=${{ github.event.inputs.p_key }}" >> $GITHUB_ENV
          echo "P_ADD=${{ github.event.inputs.p_add }}" >> $GITHUB_ENV

      - name: Print Parameters
        run: |
          echo "Project ID: $P_ID"
          echo "Project Key: $P_KEY"
          echo "Project Address: $P_ADD"
          echo "$P_ID" "$P_KEY" "$P_ADD"
          
